### PR TITLE
K1J-383: Value should not be static for logical address for recipient

### PR DESCRIPTION
**Pull request by mhornfeldt**

### CODE REVIEW

**Review by mww-sopra-steria — CHANGES_REQUESTED** [review]
This PR adds konfiguration outside of the certificate type model. Could we instead than adding it as a configuration in clinicalprocess-v4 add it to the model?

This will make sure that all configuration related to certificate types will be contained in one place.

**Comment by mhornfeldt** [comment]
> This PR adds konfiguration outside of the certificate type model. Could we instead than adding it as a configuration in clinicalprocess-v4 add it to the model?
> 
> This will make sure that all configuration related to certificate types will be contained in one place.

Add it to the model but the value will still be set from config?

**Comment by mww-sopra-steria** [comment]
> > This PR adds konfiguration outside of the certificate type model. Could we instead than adding it as a configuration in clinicalprocess-v4 add it to the model?
> > This will make sure that all configuration related to certificate types will be contained in one place.
> 
> Add it to the model but the value will still be set from config?

Yes, that would be good. Maybe att it to the Recipient that is part of the domain.

**Review by ChrilleSigerhed — APPROVED** [review]
Looks great, well done!

**Pull request merged**
