### PR TITLE
K1J-403: Midwife and Nurse should be able to forward & mark certificates ready for sign. Midwife and nurse should also be able to send like care admin.

### PR DESCRIPTION
**Pull request by ChrilleSigerhed**

### CODE REVIEW

**Review by erikagrensopra — APPROVED** [review]
Looks good!

**Comment by mikaelaromild1** [comment]
Shouldn't you only be able to mark certificate redy for sign and forward drafts if you do not have the right to sign? Maybe we need to set allowed roles in each certificate model instead, similar to SIGN or SEND.

According to the requeirements specification in Confluence, a nurse or midwife gets the same rights as a care_admin only if they do not have the right to sign.

**Review by mikaelaromild1 — CHANGES_REQUESTED** [review]
See comment

**Review by mikaelaromild1 — APPROVED** [review]
Well done :)

**Pull request merged**
